### PR TITLE
Live Preview

### PR DESCRIPTION
**Pull request by Daynlight**
* Add previe Button
* Add js script inside index.js for rendering preview and updating in live time
* Preview on right side
* Preview only for 1000px more devices
* Add index.css for button style
* Add const connection to themes inside index.js
* Add live events thath listening for user input
* Create blob and url to set previe
* Add meta data
* Add meta author
* Add meta desc
* Add meta keywords
* Add meta og data
* Add meta twitter data
* Add thumbnail https://lh3.googleusercontent.com/p/AF1QipMjTWdGPL1Ch8Q0poYcH5vhl_tvqF-1o1_4slJD=s680-w680-h510
[!Error] red error of invalid name of ion icon
image

### CODE REVIEW

**Comment by chriskthomas** [comment]
This looks great!

I'll merge it into the main branch. This will cause it to deploy on the staging version at https://linkfree.fly.dev where we can test before syncing to the production branch.

**Comment by Daynlight** [comment]
There is one problem with item rendering we need change
var linkCount = Number(additionalLinkButton.getAttribute("data-index")) ;
to
var linkCount = Number(additionalLinkButton.getAttribute("data-index")) + 1;

**Comment by Daynlight** [comment]
og:url to change too

**Comment by Daynlight** [comment]
Ok I added in new pull req

**Pull request merged**
